version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - mysql
      - minio
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2023-11-11T08-14-41Z
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9090:9090"
    volumes:
      - minio-data:/data
    command: server --console-address ":9090" /xxx/minio/data

volumes:
  mysql-data:
  minio-data:
